
DROP TABLE IF EXISTS folyamat_csoport_fcs;
CREATE TABLE folyamat_csoport_fcs
(
    fcs_id   INT AUTO_INCREMENT PRIMARY KEY,
    fcs_name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS folyamat_fo;
CREATE TABLE folyamat_fo
(
    fo_id   INT AUTO_INCREMENT PRIMARY KEY,
    fo_kod VARCHAR(50) NOT NULL,
    fcs_id  VARCHAR(250) NOT NULL,
    fo_name VARCHAR(250) NOT NULL
);

insert into folyamat_csoport_fcs (fcs_id, fcs_name) values (1, 'Dolgozók');
insert into folyamat_csoport_fcs (fcs_id, fcs_name) values (2, 'Tanulók');

INSERT INTO PUBLIC.FOLYAMAT_FO (FO_ID, FCS_ID, FO_KOD, FO_NAME) VALUES (1, 1, 'DOLGOZO_ROGZITES', 'Dolgozó rögzítése');
INSERT INTO PUBLIC.FOLYAMAT_FO (FO_ID, FCS_ID, FO_KOD, FO_NAME)VALUES (2, 1, 'DOLGOZO_MODOSITAS','Dolgozó adatainak módosítása');

INSERT INTO PUBLIC.FOLYAMAT_FO (FO_ID, FCS_ID, FO_KOD, FO_NAME) VALUES (3, 2, 'TANULO_ROGZITES', 'Tanuló felvétele');
INSERT INTO PUBLIC.FOLYAMAT_FO (FO_ID, FCS_ID, FO_KOD, FO_NAME)VALUES (4, 2, 'TANULO_CSOPORTHOZ_RENDELES','Tanulo csoporthoz rendelés');

DROP TABLE IF EXISTS tanulo_tan;
CREATE TABLE TANULO_TAN
(
    TAN_ID              INT AUTO_INCREMENT PRIMARY KEY,
    TAN_CSALADI_NEV     VARCHAR(250) NOT NULL,
    TAN_KERESZTNEV      VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS DOLGOZO_DOL;
CREATE TABLE DOLGOZO_DOL
(
    DOL_ID              INT AUTO_INCREMENT PRIMARY KEY,
    DOL_CSALADI_NEV     VARCHAR(250) NOT NULL,
    DOL_KERESZTNEV      VARCHAR(250) NOT NULL,
    DOL_BEOSZTAS        VARCHAR(64) NOT NULL
);


DROP TABLE IF EXISTS OVI_CSOPORT_OCS;
CREATE TABLE OVI_CSOPORT_OCS
(
    OCS_ID              INT AUTO_INCREMENT PRIMARY KEY,
    OCS_CSOPORT_NEV     VARCHAR(250) NOT NULL,
    OCS_VEZETO_DOL_ID          INT NOT NULL
);


DROP TABLE IF EXISTS OVI_CSOPORT_TANULO_CST;
CREATE TABLE OVI_CSOPORT_TANULO_CST
(
    CST_ID          INT AUTO_INCREMENT PRIMARY KEY,
    CST_CSOPORT_ID  INT NOT NULL,
    CST_TANUO_ID    INT NOT NULL
);

INSERT INTO PUBLIC.TANULO_TAN (TAN_ID, TAN_CSALADI_NEV, TAN_KERESZTNEV) values (1,'FÜZESI', 'OLIVÉR');
INSERT INTO PUBLIC.TANULO_TAN (TAN_ID, TAN_CSALADI_NEV, TAN_KERESZTNEV) values (2,'FÜZESI', 'MARCELL');
INSERT INTO PUBLIC.TANULO_TAN (TAN_ID, TAN_CSALADI_NEV, TAN_KERESZTNEV) values (3,'MICI', 'MACI');
INSERT INTO PUBLIC.DOLGOZO_DOL (DOL_ID, DOL_CSALADI_NEV, DOL_KERESZTNEV, DOL_BEOSZTAS) values (1,'FÜZESI', 'ZSOLT','UDVARI BOHÓC');
INSERT INTO PUBLIC.DOLGOZO_DOL (DOL_ID, DOL_CSALADI_NEV, DOL_KERESZTNEV, DOL_BEOSZTAS) values (2,'ECSERI', 'BARBARA','ÓVÓNÉNI');

INSERT INTO PUBLIC.OVI_CSOPORT_OCS (OCS_ID, OCS_CSOPORT_NEV, OCS_VEZETO_DOL_ID) VALUES (1,'ALMA CSOPORT',1);
INSERT INTO PUBLIC.OVI_CSOPORT_OCS (OCS_ID, OCS_CSOPORT_NEV, OCS_VEZETO_DOL_ID) VALUES (2,'BANÁN CSOPORT',2);

INSERT INTO PUBLIC.OVI_CSOPORT_TANULO_CST (CST_ID, CST_CSOPORT_ID, CST_TANUO_ID) VALUES (1, 1, 1);
INSERT INTO PUBLIC.OVI_CSOPORT_TANULO_CST (CST_ID, CST_CSOPORT_ID, CST_TANUO_ID) VALUES (2, 2, 2);
INSERT INTO PUBLIC.OVI_CSOPORT_TANULO_CST (CST_ID, CST_CSOPORT_ID, CST_TANUO_ID) VALUES (3, 1, 3);

/*
    TANULO_ROGZITES
    -----------------> ADATOK_ROGZITESE -------------> ROGZITETT

*/
